### ISSUE TITLE
inventory doesnt change per world group setup

### ISSUE THREAD

**Issue by halowhoflungpoo** [Gnat008/PerWorldInventory#137] opened 2016-11-11 06:48 UTC
[01:40:36] [Server thread/INFO]: HaloWhoFlungPoo left the game
[01:40:36] [Craft Scheduler Thread - 34/WARN]: Exception in thread "Craft Scheduler Thread - 34" 
[01:40:36] [Craft Scheduler Thread - 34/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.3 generated an exception while executing task 15785
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:230)
	at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:88)
	at me.gnat008.perworldinventory.data.FileWriter.lambda$saveToDatabase$0(FileWriter.java:80)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
--------------------
groups:

  world1:

    worlds:

    - JEM2

    - survival

    - skyworld
    
    default-gamemode: SURVIVAL

  world2:

    worlds:
    
    - void3

    - JEM

    - void1

    - void2

    - villages

    - world

    - void4
    
    - void6

    - void5
    
    default-gamemode: SURVIVAL

  world3:

    worlds:

    - plotme
    
    default-gamemode: CREATIVE

**Comment by Gnat008** [comment] 2016-11-11 18:34
Duplicate of #115, please take a look at that one.

**Comment by halowhoflungpoo** [comment] 2016-11-12 06:19
and the inventory not switching between groups is caused by?

**Comment by halowhoflungpoo** [comment] 2016-11-12 06:26
figured out why inventory doesn't switch between groups

**Comment by Gnat008** [comment] 2016-11-22 18:58
As seen in #115, this should be fixed with the latest on Spigot. Please chime in on that issue if so.

**Closed by Gnat008** 2016-11-22 18:58 UTC
Labels: Bug, Duplicate

**Comment by halowhoflungpoo** [comment] 2016-11-22 20:23
i just can't believe i did that Gnat008 , wow you will laugh. its working i was set as owner having all the commands including bypass. I'm sorry , what a dolt i am.

**Comment by Gnat008** [comment] 2016-11-22 20:25
haha No worries! It happens! Glad it works!
