### ISSUE TITLE
Stacktrace Inventory could not be loaded at new world

### ISSUE THREAD

**Issue by GerMcS** [Gnat008/PerWorldInventory#123] opened 2016-10-07 10:19 UTC
[12:10:56 WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.2 generated an exception while executing task 444372
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:230)
        at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:88)
        at me.gnat008.perworldinventory.data.FileWriter.lambda$saveToDatabase$0(FileWriter.java:80)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
[12:10:56 WARN]: Exception in thread "Craft Scheduler Thread - 124"
[12:10:56 WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.2 generated an exception while executing task 444369
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:224)
        at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:88)
        at me.gnat008.perworldinventory.data.FileWriter.lambda$saveToDatabase$0(FileWriter.java:80)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by Gnat008** [comment] 2016-10-07 19:17
I'm going to mark this as a duplicate of #115 to try to keep the discussion and stuff together.

**Comment by Gnat008** [comment] 2016-10-23 20:46
Closing duplicate, please see Issue #115.

**Closed by Gnat008** 2016-10-23 20:46 UTC
Labels: Bug, Critical, Duplicate
