### ISSUE TITLE
[v1.10.0] Inventory duplication on death across world groups

### ISSUE THREAD

**Issue by RoyCurtis** [Gnat008/PerWorldInventory#200] opened 2017-04-01 02:35 UTC
When a player dies in world A that is in group A, but they bed-respawn in world B that is in group B, PWI does not take this into account when saving inventory state for group A.

This results in the player's inventory being duplicated; their pre-death inventory is reloaded upon re-entering world A, whilst their items are also still on the ground.

This was previously not an issue with PWI 1.9.0.

# Testing

* Tested, **not reproducible** on both servers with PerWorldInventories **1.9.0**
* Tested and reproducible on a local testing PaperSpigot (`git-Paper-1081 (MC: 1.11.2) `) server with 1 plugin
  * PerWorldInventories **1.10.0** (spigotmc.org release)
* Tested and reproducible on a local testing PaperSpigot (`git-Paper-1077 (MC: 1.11.2) `) server with 3 plugins
  * PerWorldInventories **1.10.0** (spigotmc.org release)
  * `CleanroomGenerator, PerWorldInventory, Multiverse-Core`
* Discovered and reproducible on a live PaperSpigot (`git-Paper-1077 (MC: 1.11.2) `) server with 32 plugins
  * PerWorldInventories 1.10.0 (spigotmc.org release)
  * `CleanroomGenerator, dynmap, WorldEdit, Skript, Titanic, zPermissions, Chairs, WorldBorder, ProtocolLib, Multiverse-Core, WorldGuard, NoCheatPlus, WoodCutter, Stables, Multiverse-SignPortals, HappyPet, SQLibrary, Multiverse-Portals, Vault, Prism, GTicketMaster, Orebfuscator4, Essentials, PerWorldInventory, LWC, SignShop, VanishNoPacket, SignShopExport, CraftBook, Multiverse-NetherPortals, Dynmap-Essentials, PurpleIRC`

## Setup

* [PerWorldInventory's `config.yml`](https://gist.github.com/RoyCurtis/89c9c29fc8f0f1a03b1341a44a312acc)
* [PerWorldInventory's `worlds.yml`](https://gist.github.com/RoyCurtis/3901edd30f75506c01d587d63520ca8b)

# Reproduction

_[Video reproduction can be found here](http://vanderprot.gamealition.com/img/5fa3c.mp4)_

1. [Setup server with `world` in one group and `world_nether` in another](http://i.imgur.com/F5sBYZ4.png)
1. In `world`, place a bed and sleep in it, to set respawn point
1. Create a nether portal and go in, to go to `world_nether`
1. Spawn in an item for yourself (e.g. a beacon)
1. `/kill` - Kills your player character
1. Go back into `world_nether` using the nether portal
    * Observe, that PWI gives you the stuff you died with. If you return to your death spot, you will find the items dropped on death are still present

# Notes

* This was discovered thanks to player StitchHasAGlitch on our Survival server
* This issue originally used Multiverse for the reproduction, but I have since simplified the reproduction

**Comment by RoyCurtis** [comment] 2017-04-14 11:58
I have simplified this issue down; the reproduction no longer requires Multiverse. This issue is also present in just the vanilla worlds.

**Comment by dev-job** [comment] 2017-04-20 18:41
I notice this too, a possible would be to listen to events regarding player death and to look up the world in which they died so you can whipe the inventory of that group

**Comment by bbruno5** [comment] 2017-06-03 00:42
I have this problem too, reproducible with version 1.10.0 on Spigot 1.11.2

**Comment by Pigna** [comment] 2017-06-04 14:11
Same problem. Work around it by not letting players return to bed on death.

**Comment by Gnat008** [comment] 2017-09-16 20:39
@ScourK Would you (or anyone else here) be able to test this .jar file? I'm betting that my additions so far are too simple, but it's worth a try.

https://drive.google.com/open?id=0B7hS84xeTkpsSzRUS1FkekFGbms

**Comment by Gnat008** [comment] 2017-09-18 00:45
Based on my testing, I think that should work, but I'd feel better if someone else confirmed that.

**Comment by ScuroK** [comment] 2017-09-18 18:16
@Gnat008 i will test it now.

**Comment by ScuroK** [comment] 2017-09-18 18:34
@Gnat008 with the old one i just foudn that it even dropped some other items which i didnt hav in my inv.
ok now i test your new file.

**Comment by ScuroK** [comment] 2017-09-18 18:37
@Gnat008 
i tested your jar fie and found serious bug:
1. I died in WORLD 1
2. I respawned in WORLD 2
3. I do /back
4. I immediately die when i enter world 2. i cant enter the world anymore withoud dieing

**Comment by ScuroK** [comment] 2017-09-18 18:38
do you want to come on my server and see it?

**Comment by Gnat008** [comment] 2017-09-18 18:43
er.. right... that would make sense... stand by.

**Comment by ScuroK** [comment] 2017-09-18 18:44
sure.

**Comment by ScuroK** [comment] 2017-09-18 18:45
shit!! i downgradet again but it still kills me immediately on join....

**Comment by Gnat008** [comment] 2017-09-18 18:50
Okay, with this file, one of two things will happen: You'll die once and be fine afterwards, or you'll die once, and then never die again.
https://drive.google.com/open?id=0B7hS84xeTkpsSzRUS1FkekFGbms

**Comment by ScuroK** [comment] 2017-09-18 18:54
let my try to fix it in vanilla with a cmdblock first -.-

**Comment by ScuroK** [comment] 2017-09-18 18:58
ok now i try your fix. i hope it will work :S

**Comment by ScuroK** [comment] 2017-09-18 19:03
@Gnat008 
DUDE!!
Second thing happened!! i died once but now i cant die anymore!!
wtf what should i do now??

**Comment by ScuroK** [comment] 2017-09-18 19:09
@Gnat008 Hello?? How can i fix it? now i cant die anymore! :O

**Comment by Gnat008** [comment] 2017-09-18 21:27
Ah. I did warn you that might happen. Will look into as soon as I can, 
which will be later this evening.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by Gnat008** [comment] 2017-09-18 21:51
Ah. Think I found why it would have been inconsistent before.

https://drive.google.com/open?id=0B7hS84xeTkpsSzRUS1FkekFGbms

**Comment by ScuroK** [comment] 2017-09-19 05:19
I just downgradet to official version. Now i can die again.
I will test your latest file tonight (its morning here) and see if it fixes the dupe bug :)

**Comment by ScuroK** [comment] 2017-09-19 17:55
@Gnat008 
Bugs stil here. And killspawn after trying your latest file again... :(

And now my players even found they can dupe items if they die from fall damage...

**Comment by Gnat008** [comment] 2017-09-19 18:10
Found some bad logic. Not sure how I ever actually expected that to work way back when I wrote it...
https://drive.google.com/open?id=0B7hS84xeTkpsSzRUS1FkekFGbms

**Comment by ScuroK** [comment] 2017-09-19 18:12
you really want me to test again? -.-

**Comment by ScuroK** [comment] 2017-09-19 18:12
ok ..

**Comment by Gnat008** [comment] 2017-09-19 18:22
That's plugin development for ya. Lots and lots of testing. I don't have the necessary configuration to reproduce the issue, and even if I did, it would be better to have it confirmed by someone who isn't me.

**Comment by ScuroK** [comment] 2017-09-19 18:24
@Gnat008 
just finished testing:
killed myself with fall damage.
still killspam after /back

now i restart server without pwi so that i can see if items duped aswell.

**Comment by Gnat008** [comment] 2017-09-19 18:25
Did you only die once? Above I did say that you would have to do it more than once to fix the old data.

**Comment by ScuroK** [comment] 2017-09-19 18:25
oh let me see. give me 4 min

**Comment by ScuroK** [comment] 2017-09-19 18:29
I tested again. Every tinme i enter the world where i died i immediately get killed and the death message: "fell from a high place" appears.

**Comment by ScuroK** [comment] 2017-09-19 18:33
did you maybe send me the same file for testing again and again by mistake? because i see no change

**Comment by Gnat008** [comment] 2017-09-19 18:34
Not unless Google Drive isn't updating the file correctly.

**Comment by Gnat008** [comment] 2017-09-19 18:35
Deleted it on Drive, and did a fresh upload: https://drive.google.com/open?id=0B7hS84xeTkpsZnhsVWUzYjZRYXc

**Comment by ScuroK** [comment] 2017-09-19 18:38
Ok i will test it. 
but listen:
i just restarted the server on 1.10.0 and did /suicide to see if its only on fall damage. i only had 1 wool but it gave me 17! means: it gave me the number of items i had in my last test! somehow it remembered an old value! thats why people also told me they got the items from their LAST DEATH again! can you understand what i mean? my english is not so good

**Comment by ScuroK** [comment] 2017-09-19 18:42
im testing latest file now.

**Comment by ScuroK** [comment] 2017-09-19 18:45
@Gnat008 
Tested latest file:
Kill bug still here
Dupe bug still here

**Comment by ScuroK** [comment] 2017-09-19 19:08
what will you try next?

**Comment by ScuroK** [comment] 2017-09-23 14:51
any news here??

**Comment by Gnat008** [comment] 2017-09-23 15:13
Sorry, got sick this week and still getting over it.

**Comment by ScuroK** [comment] 2017-09-23 15:20
oh get well soon!

**Comment by BBoyJD10** [comment] 2017-09-24 22:56
Also happens with fall damage

**Comment by BBoyJD10** [comment] 2017-09-24 22:59
So when we get patch ?

**Comment by Gnat008** [comment] 2017-09-24 23:01
Hopefully soon. The weather and this cold is still kicking my ass, but I'll try to come up with something.

**Comment by BBoyJD10** [comment] 2017-09-24 23:02
Please can we have one asap.... this is ruining my network. I converted from MVI for support and this has just been appalling.

**Comment by Gnat008** [comment] 2017-09-25 00:35
@ScuroK I cannot reproduce the constant death problem using the same jar.

Made other progress though: Inventory items are correctly cleared on death. But for some reason, exp/levels aren't; I still had the exp I gave myself... Not sure why yet.

**Comment by Gnat008** [comment] 2017-09-25 02:27
For anyone interested: https://drive.google.com/open?id=0B7hS84xeTkpsZnhsVWUzYjZRYXc

**Comment by Gnat008** [comment] 2017-09-27 15:08
Based on my testing and a comment on Spigot, I'm going to mark this fixed by cf94e4d. If there are any future issues regarding death, please open a new issue.

**Closed by Gnat008** 2017-09-27 15:08 UTC
Labels: Priority: Critical, Type: Bug
