### ISSUE TITLE
No Such File Or Directory (Help)

### ISSUE THREAD

**Issue by KensonPlays** [Gnat008/PerWorldInventory#240] opened 2017-07-16 17:48 UTC
Keep getting these errors in my console and it's messing with inventories. Spigot 1.12:

WARN java.io.FileNotFoundException: plugins/PerWorldInventory/data/defaults/__default.json (No such file or directory)

ERROR An error occurred copying file '__default.json' to 'private.json': [FileNotFoundException] plugins/PerWorldInventory/data/defaults/__default.json (No such file or directory)

WARN Could not save default.json to plugins/PerWorldInventory/default.json because default.json already exists.

Any idea what's causing these? The file does exist from the third error.

Here is what the /data/ folder looks like:
http://i.imgur.com/f9ZNSLB.png

**Comment by KensonPlays** [comment] 2017-07-17 07:57
Anyone??

This is the last error we have to figure out in our console before formally launching.

**Comment by KensonPlays** [comment] 2017-07-17 18:21
It's been over 1 day, nobody's responded on the forums, or here on GitHub. Is the developer even alive?

**Comment by maxlehot1234** [comment] 2017-07-29 22:56
Same error here sometimes since few months. Dev NEVER update his plugin, so we need to deal with this error..........................

**Comment by ljacqu** [comment] 2017-08-13 09:05
I think this is a duplicate of #204 as I'm not able to reproduce it with the codebase in its newest version. 

Could you try using the perworldinventory-1.10.1.jar from https://github.com/ljacqu/PerWorldInventory/tree/latest-jar ?

**Comment by Gnat008** [comment] 2017-09-27 17:55
Fixed in v1.11.

**Closed by Gnat008** 2017-09-27 17:55 UTC
