### ISSUE TITLE
duplacate bug

### ISSUE THREAD

**Issue by dwa1275** [Gnat008/PerWorldInventory#228] opened 2017-06-21 00:15 UTC
when players dine in a world, spawn in the main world, then go back, player get double the items, this is a bug that multiverse inventories was able to fix, shouldn't be that hard to fix

**Comment by ScuroK** [comment] 2017-09-09 12:41
i have the same issue.

**Comment by Gnat008** [comment] 2017-09-16 20:17
Duplicate of #200. Closing duplicates to clean things up a bit; see that issue for further comments/discussion. Thanks!

**Closed by Gnat008** 2017-09-16 20:17 UTC
Labels: Priority: Critical, Status: Duplicate, Type: Bug
