### ISSUE TITLE
MAJOR: Dupe Glitch in latest version

### ISSUE THREAD

**Issue by ScuroK** [Gnat008/PerWorldInventory#220] opened 2017-05-09 10:59 UTC
If a player dies from fall damage he will respawn in another world. If he returns to the place of death his items will be duped. 

He will keep them in his inventory and also find them on the floor aswell! please fix ASAP! thanks <3

**Comment by Pigna** [comment] 2017-05-09 16:42
I can confirm. Way i 'fixed' this is to turn off bedspawn in all worlds and if a player dies in one world he returns to the spawn of that world. Not the best solution.... but still beter then a dupe bug

**Comment by ScuroK** [comment] 2017-05-10 08:54
@Gnat008 any chance u can fix this soon?

**Comment by ScuroK** [comment] 2017-09-09 12:20
@Gnat008 pls pls pls? :) <3

**Comment by Gnat008** [comment] 2017-09-16 20:17
Duplicate of #200. Closing duplicates to clean things up a bit; see that issue for further comments/discussion. Thanks!

**Closed by Gnat008** 2017-09-16 20:17 UTC
Labels: Priority: Critical, Status: Duplicate, Type: Bug
