### ISSUE TITLE
generated an exception while executing task 395216

### ISSUE THREAD

**Issue by Elioz** [Gnat008/PerWorldInventory#146] opened 2016-12-06 15:00 UTC
Hello!

The plugin throw this error in console,
[09:31:12] [Craft Scheduler Thread - 3178/WARN]: Exception in thread "Craft Scheduler Thread - 3178" 
[09:31:12] [Craft Scheduler Thread - 3177/WARN]: Exception in thread "Craft Scheduler Thread - 3177" 
[09:31:12] [Craft Scheduler Thread - 3178/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.3 generated an exception while executing task 395216
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:230)
	at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:88)
	at me.gnat008.perworldinventory.data.FileWriter.lambda$saveToDatabase$0(FileWriter.java:80)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[09:31:12] [Craft Scheduler Thread - 3177/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.3 generated an exception while executing task 395217
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:230)
	at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:88)
	at me.gnat008.perworldinventory.data.FileWriter.lambda$saveToDatabase$0(FileWriter.java:80)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

what can it be?

**Comment by sloanr333** [comment] 2016-12-06 16:15
I believe this is the same issue as #115 which was fixed ( i think ) in the newest update, 1.9.0 which you can find here: [https://www.spigotmc.org/resources/per-world-inventory.4482/updates](https://www.spigotmc.org/resources/per-world-inventory.4482/updates)

**Comment by Gnat008** [comment] 2016-12-13 18:44
As @sloanr333 said, duplicate of #115 which is now fixed.

**Closed by Gnat008** 2016-12-13 18:44 UTC
Labels: Duplicate, Fixed
