### ISSUE TITLE
Inventory's wont switch [High priority]

### ISSUE THREAD

**Issue by bolleboor** [Gnat008/PerWorldInventory#116] opened 2016-09-24 10:23 UTC
Hello I found an issue for the switch
As you join an other world the inventory wont switch
Can you fix it?

PasteBin: [http://pastebin.com/v5iBHyRS]

Thanks,
Greetings bolleboor

**Comment by Gnat008** [comment] 2016-10-07 19:18
I'm going to mark this as a duplicate of #115 to try to keep the discussion and stuff together.

**Comment by Gnat008** [comment] 2016-10-23 20:46
Closing duplicate, please see Issue #115.

**Closed by Gnat008** 2016-10-23 20:46 UTC
Labels: Bug, Critical, Duplicate
