### ISSUE TITLE
Plugin not working and spitting out errors

### ISSUE THREAD

**Issue by lordsherman** [Gnat008/PerWorldInventory#246] opened 2017-08-09 10:08 UTC
Not sure what I am doing wrong I setup the worlds config properly with my normal worlds under default and then a minigames world under a minigame tag, when I reload this is the warnings the console spits out:

09.08 04:01:32 [Server] WARN at java.lang.Thread.run(Thread.java:745)
09.08 04:01:32 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
09.08 04:01:32 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
09.08 04:01:32 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
09.08 04:01:32 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
09.08 04:01:32 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
09.08 04:01:32 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09.08 04:01:32 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
09.08 04:01:32 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
09.08 04:01:32 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
09.08 04:01:32 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
09.08 04:01:32 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
09.08 04:01:32 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
09.08 04:01:32 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
09.08 04:01:32 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
09.08 04:01:32 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
09.08 04:01:32 [Server] WARN at me.gnat008.perworldinventory.PerWorldInventory.onCommand(PerWorldInventory.java:295)
09.08 04:01:32 [Server] WARN at me.gnat008.perworldinventory.commands.ReloadCommand.executeCommand(ReloadCommand.java:28)
09.08 04:01:32 [Server] WARN at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
09.08 04:01:32 [Server] WARN at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
09.08 04:01:32 [Server] WARN at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
09.08 04:01:32 [Server] WARN at java.io.FileInputStream.<init>(FileInputStream.java:138)
09.08 04:01:32 [Server] WARN at java.io.FileInputStream.open(FileInputStream.java:195)
09.08 04:01:32 [Server] WARN at java.io.FileInputStream.open0(Native Method)
09.08 04:01:32 [Server] WARN java.io.FileNotFoundException: plugins/PerWorldInventory/data/defaults/__default.json (No such file or directory)
09.08 04:01:32 [Server] ERROR An error occurred copying file '__default.json' to 'Minigames.json': [FileNotFoundException] plugins/PerWorldInventory/data/defaults/__default.json (No such file or directory)
09.08 04:00:48 [Server] INFO Traveler: [Traveler] Mavzi
09.08 04:00:48 [Server] INFO Admins: [Owner] Lord_Sherman
09.08 04:00:43 [Server] INFO Fetched due players (0 found).
09.08 04:00:43 [Server] INFO Fetching all due players...
09.08 03:59:42 [Server] INFO Traveler: [Traveler] Mavzi
09.08 03:59:42 [Server] INFO Admins: [Owner] Lord_Sherman
09.08 03:58:36 [Server] INFO Traveler: [Traveler] Mavzi
09.08 03:58:36 [Server] INFO Admins: [Owner] Lord_Sherman
09.08 03:57:31 [Server] INFO Traveler: [Traveler] Mavzi
09.08 03:57:31 [Server] INFO Admins: [Owner] Lord_Sherman
09.08 03:56:37 [Server] INFO Updating coupon list...
09.08 03:56:32 [Server] INFO Saved the world
09.08 03:56:32 [Server] INFO Saving...
09.08 03:56:32 [Server] INFO Saving is already turned on
09.08 03:56:32 [Multicraft] Auto-saving world...
09.08 03:56:25 [Server] INFO Traveler: [Traveler] Mavzi
09.08 03:56:25 [Server] INFO Admins: [Owner] Lord_Sherman
09.08 03:56:17 [Server] INFO Warning Ground items will be removed in 20 seconds!
09.08 03:55:53 [Server] WARN at java.lang.Thread.run(Thread.java:745)
09.08 03:55:53 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
09.08 03:55:53 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
09.08 03:55:53 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
09.08 03:55:53 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
09.08 03:55:53 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
09.08 03:55:53 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09.08 03:55:53 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
09.08 03:55:53 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
09.08 03:55:53 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
09.08 03:55:53 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
09.08 03:55:53 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
09.08 03:55:53 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
09.08 03:55:53 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
09.08 03:55:53 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
09.08 03:55:53 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
09.08 03:55:53 [Server] WARN at me.gnat008.perworldinventory.PerWorldInventory.onCommand(PerWorldInventory.java:295)
09.08 03:55:53 [Server] WARN at me.gnat008.perworldinventory.commands.ReloadCommand.executeCommand(ReloadCommand.java:28)
09.08 03:55:53 [Server] WARN at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
09.08 03:55:53 [Server] WARN at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
09.08 03:55:53 [Server] WARN at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
09.08 03:55:53 [Server] WARN at java.io.FileInputStream.<init>(FileInputStream.java:138)
09.08 03:55:53 [Server] WARN at java.io.FileInputStream.open(FileInputStream.java:195)
09.08 03:55:53 [Server] WARN at java.io.FileInputStream.open0(Native Method)
09.08 03:55:53 [Server] WARN java.io.FileNotFoundException: plugins/PerWorldInventory/data/defaults/__default.json (No such file or directory)
09.08 03:55:53 [Server] ERROR An error occurred copying file '__default.json' to 'Minigames.json': [FileNotFoundException] plugins/PerWorldInventory/data/defaults/__default.json (No such file or directory)

**Comment by maxlehot1234** [comment] 2017-08-11 01:26
Same for me, but do not expect an update. Devs simply leave this plugin and will NEVER update it :(

Too many errors/bugs, etc and no answer, no fix, etc :(

**Comment by ljacqu** [comment] 2017-08-13 09:05
Duplicate of #240

**Comment by Gnat008** [comment] 2017-09-27 17:55
Fixed in v1.11.

**Closed by Gnat008** 2017-09-27 17:55 UTC
