### ISSUE TITLE
Remember player position

### ISSUE THREAD

**Issue by luuxter** [Gnat008/PerWorldInventory#250] opened 2017-08-27 19:05 UTC
Hello,

I have been looking for a way to track the location of a player in a certain world. I am working on a server with multiple worlds, 'lobby', 'survival', 'skyblock' and 'parkour' for now. I use MultiVerse and this plugin to save players' inventories per world. Now, I was wondering: can this plugin, like MultiVerse Inventories, save a players' location per world? So, for example, a player logs in to the server. He ends up in the lobby, which is good. Then he chooses to play survival. He goes into a mine and makes a little house. When he goes back to the lobby, he needs to spawn in the default lobby spawn point. But, when he goes back to the survival world, he needs to spawn where we was when he logged out.

If you know how I can do this or if there is a way outside your plugin of doing this, I would be forever grateful. I have not been able to find anything on the internet, unfortunately.

Regards,
Luuxter

**Comment by Gnat008** [comment] 2017-09-27 21:21
Duplicate of #108

**Closed by Gnat008** 2017-09-27 21:21 UTC
Labels: Status: Duplicate
