### ISSUE TITLE
NullPointerException - FileWriter.getFile

### ISSUE THREAD

**Issue by mibby** [Gnat008/PerWorldInventory#130] opened 2016-10-30 15:16 UTC
PerWorldInventory v1.8.3
Paper (Spigot 1.10.2) dev 898

Config
http://paste.ubuntu.com/23402771/

Worlds
http://paste.ubuntu.com/23402776/

@Gnat008  Getting these errors frequently. 
```
[02:15:15] [Craft Scheduler Thread - 16/WARN]: [PerWorldInventory] Plugin PerWorldInventory v1.8.3 generated an exception while executing task 694
java.lang.NullPointerException
	at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:230) ~[?:?]
	at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:88) ~[?:?]
	at me.gnat008.perworldinventory.data.FileWriter.lambda$saveToDatabase$0(FileWriter.java:80) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.2.jar:git-Paper-898]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.10.2.jar:git-Paper-898]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.10.2.jar:git-Paper-898]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by Gnat008** [comment] 2016-10-30 17:18
Duplicate of #115

**Closed by Gnat008** 2016-10-30 17:18 UTC
Labels: Bug, Critical, Duplicate
