### ISSUE TITLE
OPs have no separate inventory

### ISSUE THREAD

**Issue by TheOtakuJames** [Gnat008/PerWorldInventory#56] opened 2016-06-29 06:20 UTC
Hia,

On my server, if you are OP your inventory goes across worlds, which is really annoying. 
It is fine for all the non-OP players, but the 2 of us that are OP are finding it very irritating. I am using the latest version of PWI (1.7.5), and the latest Spigot 1.10.

How can this be fixed?
Thanks!

**Comment by Gnat008** [comment] 2016-06-29 14:43
The latest version (1.7.6) should contain a fix for this. If it does not, check your permissions plugin.

**Comment by TheOtakuJames** [comment] 2016-06-29 21:34
Ok, I downloaded the latest version, and I still have the same inventory across all my worlds. It always used to be fine, only at 1.7.5 did the error occur so it's not my permissions. I checked just to make sure  and nothing is out of the ordinary :/

**Comment by Gnat008** [comment] 2016-06-29 21:38
Just to be sure, what permission nodes do you have on you that are related to PWI? Or are you using '*' ?

**Comment by TheOtakuJames** [comment] 2016-06-29 21:41
I have none in my permissions.yml (I'm using PEX as my permissions plugin), and in my own file I don't have any related to PWI (I only have a couple essentials ones that I was fiddling with ages ago). 
I never added any permissions to people, as I wanted every world to be separate, which for every player other than the OPs is working. Are there any I should add to myself?

**Comment by Gnat008** [comment] 2016-06-29 23:00
Am still unable to reproduce, with or without Pex, as Op. I'm thinking you have to have a permissions issue. What nodes do you have?

**Comment by TheOtakuJames** [comment] 2016-06-30 06:20
My personal ones are:
mcmmo.ability.mining.blastmining.detonate
essentials.nick.format
FancyPortals.Create
vanish.*
namecolor.gray
*

**Comment by Gnat008** [comment] 2016-06-30 14:55
So you DO have the '*' permission?

**Comment by HeadlessJoey** [comment] 2016-06-30 15:00
Hi, I was keeping an eye on this one since I had a very similar problem. However I did fix it (was having this problem for all my users and had to add this specific permission to the default group).
Just add this permissions to your OP players:
-perworldinventory.bypass.*

Make sure to add it at the very top of the permission list if you are using PEX. All negative permissions should be at the top otherwise they might not work.

**Comment by TheOtakuJames** [comment] 2016-06-30 21:35
@Gnat008 Yes, the normal Spigot or whatever it is * but not the perworldinventory.*
@HeadlessJoey Ok, I'll test this out now...
That seems to have worked! I moved things around from one inventory and they are different in the other worlds. Thanks so much!

**Comment by Gnat008** [comment] 2016-06-30 22:06
"*" means you have ALL permissions for EVERY plugin, and really should not be used, for exactly the reason shown here. It causes weirdness and unintentional side effects.

**Comment by TheOtakuJames** [comment] 2016-06-30 22:42
Doesn't OP have all permission nodes automatically? I don't remember adding * to my permissions.

**Comment by Gnat008** [comment] 2016-06-30 22:48
Op does not. It depends on how each author made his plugin if Ops have a permission or not.

**Comment by aycgit** [comment] 2016-07-04 07:13
i think this issue can be closed because it was just the permissions

**Closed** 2016-07-04 15:00 UTC
Labels: Cannot Reproduce
