### ISSUE TITLE
Error while starting plugin

### ISSUE THREAD

**Issue by Superdarco** [Gnat008/PerWorldInventory#212] opened 2017-04-22 18:42 UTC
Hi, This plugin is very good but recently I am getting this message, I hope you fix it in the next version

[13:36:40] [Server thread/INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.10.0
[13:36:40] [Server thread/WARN]: [PerWorldInventory] Could not save default.json to plugins\PerWorldInventory\default.json because default.json already exists.
[13:36:41] [Server thread/INFO]: [PerWorldInventory] Registering listeners...
[13:36:41] [Server thread/INFO]: [PerWorldInventory] Listeners registered!
[13:36:41] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'ASkyBlock.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:36:41] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:36:41] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'juegos.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:36:41] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:36:41] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'Candy.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:36:41] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:36:41] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'Colores.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:36:41] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:36:41] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'Double.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:36:41] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:36:41] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'Village.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:36:41] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:36:41] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'Safari.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:36:41] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:36:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:36:41] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:36:41] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:36:41] [Server thread/INFO]: [PerWorldInventory] Registering commands...
[13:36:41] [Server thread/INFO]: [PerWorldInventory] Commands registered!
[13:36:41] [Server thread/INFO]: [PerWorldInventory] Vault found! Hooking into it...
[13:36:41] [Server thread/INFO]: [PerWorldInventory] Hooked into Vault!

I hope this log is useful to you, if you take the DEBUG on, let me know and I'll give it to you.

**Comment by Gnat008** [comment] 2017-04-22 18:53
Duplicate of #204. Please see that issue. :)

**Closed by Gnat008** 2017-04-22 18:53 UTC
Labels: Bug, Duplicate

**Comment by Superdarco** [comment] 2017-04-22 19:02
Oh ok sorry
