### ISSUE TITLE
Doubling Money balance

### ISSUE THREAD

**Issue by HopeIce** [Gnat008/PerWorldInventory#149] opened 2016-12-12 01:19 UTC
Hey! I was wondering if you could tell me why the balance seems to double when players switch between worlds? I wasn't sure. Something seems to double the money when they go between creative and survival. Any help would be wonderful :)

**Comment by ljacqu** [comment] 2016-12-12 06:05
Duplicate of #148

**Comment by HopeIce** [comment] 2016-12-12 15:02
Ok? Then how do I fix this xD

**Comment by sloanr333** [comment] 2016-12-12 16:12
That means that, unfortunately, it's an open issue that someone else has already reported. Someone will look into it as soon as there is time, and if any information is learned or a fix is made for it, you'll probably want to keep an eye on thread #148, as it was posted first and is considered the "master" thread for the issue. :)

**Comment by Gnat008** [comment] 2016-12-13 18:48
Yes, please look at #148 for this issue, and continue any discussion there to keep things all in one place. :)

**Closed by Gnat008** 2016-12-13 18:48 UTC
Labels: Duplicate
