### ISSUE TITLE
Doesn't work... tried different versions, same error

### ISSUE THREAD

**Issue by lester695** [Gnat008/PerWorldInventory#311] opened 2018-03-06 10:41 UTC
[11:40:10 INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.11.5
[11:40:11 ERROR]: Error occurred while enabling PerWorldInventory v1.11.5 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getAndValidatePostConstructMethod(PostConstructMethodInvoker.java:47) ~[?:?]
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getPostConstructMethods(PostConstructMethodInvoker.java:34) ~[?:?]
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:23) ~[?:?]
        at ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255) ~[?:?]
        at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182) ~[?:?]
        at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
        at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:197) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:120) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 20 more

**Comment by ljacqu** [comment] 2018-03-06 17:58
Duplicate of #260

**Comment by Gnat008** [comment] 2018-03-06 17:59
See linked issue above. ^

**Closed by Gnat008** 2018-03-06 17:59 UTC
Labels: Status: Duplicate
