### ISSUE TITLE
Task #120 for PerWorldInventory v1.9.0 generated an exception

### ISSUE THREAD

**Issue by MinecraftKid45** [Gnat008/PerWorldInventory#160] opened 2017-01-09 19:39 UTC
So, while this does not seem to effect or hurt anything, it is still annoying! I keep getting this error in my Console:

 [PerWorldInventory] Task #120 for PerWorldInventory v1.9.0 generated an exception
09.01 14:27:54 [Server] INFO java.lang.NullPointerException
09.01 14:27:54 [Server] INFO at me.gnat008.perworldinventory.data.players.PWIPlayerManager.lambda$scheduleRepeatingTask$0(PWIPlayerManager.java:333) ~[?:?]
09.01 14:27:54 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
09.01 14:27:54 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
09.01 14:27:54 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
09.01 14:27:54 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
09.01 14:27:54 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
09.01 14:27:54 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
09.01 14:27:54 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by ljacqu** [comment] 2017-01-09 19:56
Duplicate of #147 #155

**Comment by MrOpposite** [comment] 2017-01-10 06:39
I left steps to reproduce on #147

**Comment by Gnat008** [comment] 2017-01-10 23:47
Please post the contents of you worlds.yml file in issue #147.

**Closed by Gnat008** 2017-01-10 23:47 UTC
Labels: Bug, Duplicate

**Comment by clowrym** [comment] 2017-02-11 18:52
same issue here are well. 

`[11:37:12] [Server thread/WARN]: [PerWorldInventory] Task #26 for PerWorldInventory v1.9.0 generated an exception
java.lang.IllegalArgumentException: No enum constant org.bukkit.GameMode.0
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_111]
at org.bukkit.GameMode.valueOf(GameMode.java:1) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
at me.gnat008.perworldinventory.data.players.PWIPlayerManager.lambda$scheduleRepeatingTask$0(PWIPlayerManager.java:329) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

worlds.yml:


`# In this file you define your groups and the worlds in them.
# Follow this format:
# groups:
#   default:
#     worlds:
#     - world
#     - world_nether
#     - world_the_end
#     default-gamemode: SURVIVAL
#   creative:
#     worlds:
#     - creative
#     default-gamemode: CREATIVE
#
# 'default' and 'creative' are the names of the groups
# worlds: is a list of all worlds in the group
# If you have 'manage-gamemodes' set to true in the main config, the server
# will use the 'default-gamemode' here to know what gamemode to put users in.
groups:
  creative:
    worlds:
    - world
    - world_nether
    - world_the_end
    default-gamemode: CREATIVE
  default:
    worlds:
    - Bukkit
    - Bukkit_nether
    default-gamemode: SURVIVAL
  default1:
    worlds:
    - Parkour
    - Hunger
    default-gamemode: ADVENTURE
  default2:
    worlds:
    - Hogwarts1.0
    default-gamemode: ADVENTURE`
