### ISSUE TITLE
people straight up losing their inventory when they switch worlds !

### ISSUE THREAD

**Issue by J2D22** [Gnat008/PerWorldInventory#115] opened 2016-09-20 15:18 UTC
Hello, this has been hapenning for a week now.
People have been going to our minigame world then coming back to find that everything they had in their inventory has a red 0 on it or has simply disappeared. also, i am getting some errors in the console :

http://pastebin.com/nZiJnK0m

Please tell me how to fix this ASAP as we have been losing players to this issue.

**Comment by ljacqu** [comment] 2016-09-29 17:35
Duplicate of #86 (just dropping a comment so the issues get linked, don't mind me)

**Comment by MithrandirCraft** [comment] 2016-10-01 13:24
That's right :/ I posted lots of logs here by the way: https://github.com/Gnat008/PerWorldInventory/issues/107

**Comment by Gnat008** [comment] 2016-10-23 19:49
Could someone getting the NullPointerExceptions try this version and send me the output? It prints a message to the console/server log when saving to check of the group name is null.
https://www.dropbox.com/s/f09y4f9kxllyq9t/perworldinventory-1.8.4.jar?dl=0

**Comment by mibby** [comment] 2016-10-30 18:53
Using the debug build, haven't had an exception occur yet. Just [DEBUG] group spam.

```
[11:18:46] [Craft Scheduler Thread - 19/INFO]: [PerWorldInventory] [DEBUG] Build
[11:18:46] [Craft Scheduler Thread - 16/INFO]: [PerWorldInventory] [DEBUG] default
[11:18:46] [Craft Scheduler Thread - 21/INFO]: [PerWorldInventory] [DEBUG] default
[11:18:46] [Craft Scheduler Thread - 22/INFO]: [PerWorldInventory] [DEBUG] Build
```

**Comment by mibby** [comment] 2016-11-02 14:58
@Gnat008 Any update? :( The only thing the debug build spams in the log / console is the world groups. No exceptions occur with that version.

http://paste.ubuntu.com/23416447/

```
  Build:
    worlds:
    - Build1
    - Build2
  default:
    worlds:
    - Hub
    - world
```

**Comment by sloanr333** [comment] 2016-11-02 22:03
Are you still getting the null pointer errors?

If so, can you get another paste of the errors like you did in OP, but include the debug lines around it too? It also might help to turn on debug-mode inside PWI's config.yml, then do a "pwi reload" command.

**Comment by mibby** [comment] 2016-11-03 02:12
> The only thing the debug build spams in the log / console is the world groups. No exceptions occur with that version.

**Comment by sloanr333** [comment] 2016-11-03 15:07
I assume people are still losing their inventories.

> It also might help to turn on debug-mode inside PWI's config.yml, then do a "pwi reload" command.

**Comment by mibby** [comment] 2016-11-03 15:35
I personally have not heard from anyone about losing their inventories. Just the exception occurring. https://github.com/Gnat008/PerWorldInventory/issues/130 My issue was merged into this one.

**Comment by Gnat008** [comment] 2016-11-04 23:18
...So the special version I linked above doesn't cause the exception? I don't see how that's possible, I just added a log message. O.o

**Comment by mibby** [comment] 2016-11-05 12:49
Not that I have seen, no. Though the only change I personally made was disabling ```share-if-unconfigured``` and manually adding another world group just for the unlisted worlds. So perhaps the exception occurs when trying to load / save inventories in worlds that are set to share if unconfigured?

**Comment by Gnat008** [comment] 2016-11-05 18:21
That shouldn't be making a difference... If this is a test server, could you undo your configuration changes, and see if it happens again?

**Comment by mibby** [comment] 2016-11-05 23:27
Unfortunately it is not a test server. I self compiled the source as of this commit https://github.com/Gnat008/PerWorldInventory/commit/349a006aac87be524894784722aa1898ef686a6f and haven't received an exception. So either it is fixed in the main branch or was caused by the share-if-unconfigured.

**Comment by Gnat008** [comment] 2016-11-06 00:09
New test version with better debug messages around this issue and some simplified code: https://www.dropbox.com/s/f09y4f9kxllyq9t/perworldinventory-1.8.4.jar?dl=0
Still need the output from this version from someone with the issue. You can also build the 115-fix branch if you're inclined.

**Comment by BabeElijah** [comment] 2016-11-07 18:10
> New test version with better debug messages around this issue and some simplified code: 
perworldinventory-1.8.4.zip

Still need the output from this version from someone with the issue. You can also build the 115-fix branch if you're inclined.

Important: If you are giving logs, please either upload the log file itself, or paste the contents to hastebin.com and then post the link to it here! This ensures the easiest readability and formatting!

Don't seem to be getting an error right now, but will keep on testing.

**Comment by Gnat008** [comment] 2016-11-10 21:43
We are quickly running out of places where this fault could be hiding.... Lets try this version. And make sure to enable debugging if you try this, I desperately need that debug output!

[perworldinventory-1.8.4.zip](https://github.com/Gnat008/PerWorldInventory/files/584509/perworldinventory-1.8.4.zip)

**Comment by Gnat008** [comment] 2016-11-10 22:58
For @Elijeh (New)
[perworldinventory-1.8.4.zip](https://github.com/Gnat008/PerWorldInventory/files/584624/perworldinventory-1.8.4.zip)

**Comment by Elijeh** [comment] 2016-11-10 23:06
With debug-mode disabled, I haven't been receiving any errors from the plugin (yet).

However, when I stop the server & start the server up again, I **think** player's inventories reset? I know this happened in the previous version you sent me.

**Comment by Gnat008** [comment] 2016-11-10 23:09
This is probably because the error only happens on data save, which is every 5 minutes [by default, configurable]. Which is why it's easier to just leave the server after changing worlds.

**Comment by Elijeh** [comment] 2016-11-10 23:13
Alright. well everything seems to be running smoothly now.

**Comment by Elijeh** [comment] 2016-11-10 23:30
Oh wait, I'm getting errors now:
https://gyazo.com/b3754382213bc11348c80f212d5e11ab.png

**Comment by Gnat008** [comment] 2016-11-10 23:32
Okay, I need the debug output leading up to that.

**Comment by Gnat008** [comment] 2016-11-10 23:32
Actually the debug i need is when you leave the server, not from staying.

**Comment by Elijeh** [comment] 2016-11-10 23:35
https://gyazo.com/c4aa6db0adca5250b1968876e6ab4f5a.png

(Lunix_HallowsYT & 2good2betrue are both online, they didn't leave the server)

**Comment by Elijeh** [comment] 2016-11-10 23:37
Oh okay, when I leave the server & join again, my whole inventory resets.

**Comment by Gnat008** [comment] 2016-11-10 23:39
Could you check your server log file, and not the console? The vital stuff is missing from that shot.

**Comment by Elijeh** [comment] 2016-11-10 23:40
`[15:36:25] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Player 'Elijeh' quit! Checking cache
[15:36:25] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Saving logout data for player 'Elijeh'...
[15:36:25] [Craft Scheduler Thread - 122/INFO]: [PerWorldInventory] [DEBUG] Creative
[15:36:25] [Craft Scheduler Thread - 122/INFO]: [PerWorldInventory] [DEBUG] plugins\PerWorldInventory\data\60ed511b-d0e1-4cc1-ab5f-b8bfbea9c53d
[15:36:25] [Craft Scheduler Thread - 122/INFO]: [PerWorldInventory] [DEBUG] Saving data for player 'Elijeh' in file 'plugins\PerWorldInventory\data\60ed511b-d0e1-4cc1-ab5f-b8bfbea9c53d\Creative.json'
[15:36:25] [Craft Scheduler Thread - 122/INFO]: [PerWorldInventory] [DEBUG] Writing player data for player 'Elijeh' to file`

**Comment by Elijeh** [comment] 2016-11-10 23:41
http://pastebin.com/Q7ntiFER

**Comment by Gnat008** [comment] 2016-11-10 23:41
You did extract the plugin file from the .zip file attached to the comment, right...?

**Comment by Elijeh** [comment] 2016-11-10 23:42
Yes

**Comment by Gnat008** [comment] 2016-11-10 23:43
Just for giggles, could you delete the installed PWI .jar file, and re-extract it?

**Comment by Elijeh** [comment] 2016-11-10 23:47
Done, but still get the same results.

**Comment by Gnat008** [comment] 2016-11-10 23:48
And you did restart the server after changing the .jar?

**Comment by Elijeh** [comment] 2016-11-10 23:48
Of course

**Comment by Gnat008** [comment] 2016-11-10 23:59
Would I be able to join the server to try to figure this out? There should be additional messages that are logged.

**Comment by Elijeh** [comment] 2016-11-11 00:02
Sure, try connecting with: 75.175.71.215

**Comment by Elijeh** [comment] 2016-11-11 00:03
Sure, 75.175.71.215

**Comment by Elijeh** [comment] 2016-11-11 00:07
Sure, IP is: candy-paradise.us.to

**Comment by Gnat008** [comment] 2016-11-11 00:54
Woo more debug messages! 
[perworldinventory-1.8.4.zip](https://github.com/Gnat008/PerWorldInventory/files/584790/perworldinventory-1.8.4.zip)

**Comment by Gnat008** [comment] 2016-11-11 01:20
Hopefully the last!
[perworldinventory-1.8.4.zip](https://github.com/Gnat008/PerWorldInventory/files/584838/perworldinventory-1.8.4.zip)

**Comment by Gnat008** [comment] 2016-11-11 01:39
Not the last.
[perworldinventory-1.8.4.zip](https://github.com/Gnat008/PerWorldInventory/files/584857/perworldinventory-1.8.4.zip)

**Comment by Sikatsu** [comment] 2016-11-20 23:49
I have this on 1.11 too. Any news?

**Comment by Sikatsu** [comment] 2016-11-20 23:57
Could you tell me exactly what I should do so we can solve this issue? On 1.10.2 everything worked fine, on 1.11 it doesn't.

I'll be more then glad to help when I wake up. I guess it isn't save to use on a production server?

**Comment by Sikatsu** [comment] 2016-11-21 00:05
I will test v1.8.4 when I wake up. ~9hrs from now. As soon as the error shows up i'll send the error which I guess has extra messages?

Would really like to see this fixed so I can safely use it on 1.11 =)

**Comment by Gnat008** [comment] 2016-11-21 00:07
Yeah. The odd thing with this is the behavior of the error actually happening changed seemingly randomly during the various iterations of the test files I put up. :/ Then they appeared to stop completely, and I've yet to hear back from the guy about them returning.

**Comment by Sikatsu** [comment] 2016-11-21 00:09
That's weird. Well, on 1.11 it's being a bit weird to, as it doesn't seem to happen on a certain command usage. However, it happens quite frequently with all players.

Will it help if I use that test version and check, or?

**Comment by Gnat008** [comment] 2016-11-21 00:11
What command does it work for?

**Comment by Sikatsu** [comment] 2016-11-21 00:15
Sorry for the misunderstanding.

I meant, that whatever command I use, it doesn't seem to trigger the error. However, it seems to be randomly appearing by just being online. It usually comes in 2 exact the same errors at the same time on an interval or something.

I do have an test server where the error appeared.

**Comment by Gnat008** [comment] 2016-11-21 00:16
That's because it's thrown when data is being saved to the disk, which happens every 5 minutes by default (configurable).

But the setWorldDefault command works just fine?

**Comment by Sikatsu** [comment] 2016-11-21 00:20
It's most likely that being the issue, yes. However a player must be online.

I don't know about that command and didn't test it to be honest. (I'm currently on my phone)

Not sure what time zone you live, but I could get back to this on 1.8.4 version in around 9hours if that helps you more?

**Comment by Gnat008** [comment] 2016-11-21 00:35
Yeah, worth a shot. I'm EDT, timewise.

**Comment by Sikatsu** [comment] 2016-11-21 10:14
So, what did you actually do with 1.8.4?

I don't seem to have the error anymore.. for now atleast

**Comment by Elijeh** [comment] 2016-11-21 10:20
Haven't received any errors or problems with the latest jar you put up (1.8.4).

**Comment by Gnat008** [comment] 2016-11-21 17:52
Literally the only changes were with the debug messages. No other code was changed. Which is why I really do not understand it.

Inventories have been switching just fine, as they should?

**Comment by Sikatsu** [comment] 2016-11-21 17:56
That is really weird, because if I downgrade the error shows up again, but on 1.8.4 it doesn't.. and it's for both me and Elijeh it seems.

So far so good.

**Comment by Gnat008** [comment] 2016-11-21 21:43
@Sikatsu Do you have a test server to try this version on? It has a lot of changes that are different from the 1.8.4 version above. Everything works on my servers, but then that seems to always be the case... I don't really want to mess up your production server if I don't have to though.

And @Elijeh as I recall doesn't have one, so up to his discretion.
[perworldinventory-1.9.0.zip](https://github.com/Gnat008/PerWorldInventory/files/604840/perworldinventory-1.9.0.zip)

**Comment by Sikatsu** [comment] 2016-11-21 21:50
Sure, let me just upload it to my test server now. 

185.133.72.30:25576

Running 1.11

**Comment by Gnat008** [comment] 2016-11-21 22:12
[perworldinventory-1.9.0.zip](https://github.com/Gnat008/PerWorldInventory/files/604908/perworldinventory-1.9.0.zip)

**Comment by Sikatsu** [comment] 2016-11-21 22:15
Should be updated. I'm off in around 45~minutes.

**Comment by Gnat008** [comment] 2016-11-21 22:36
I am back.

**Comment by Sikatsu** [comment] 2016-11-21 23:07
Sorry, I didn't see your message.

I took a look at the console and found errors:

http://pastebin.com/tcQ06Ez3

http://pastebin.com/nNkDQcq3

**Comment by Gnat008** [comment] 2016-11-21 23:10
That told me what I needed to know. Now for the investigation... Thanks!

**Comment by Sikatsu** [comment] 2016-11-21 23:11
It's still giving the error without players btw!

Glad I could help, I'm going to sleep. If you need more help I'll be back tomorrow!

**Comment by Gnat008** [comment] 2016-11-21 23:12
Yeah that's because it errors before it sets the player as saved, so each time it loops the player is still unsaved, so it tries again.

**Comment by Sikatsu** [comment] 2016-11-21 23:16
Ahh I see, thanks for the explanation!

**Comment by Gnat008** [comment] 2016-11-21 23:32
@Sikatsu Anytime!
Tomorrow, could you enable debugging in the PWI config, and trying again? I need the debug output right up to the error.

**Comment by Sikatsu** [comment] 2016-11-21 23:34
Sure!

In the morning I have to do some stuff, however if you leave a pm here as
soon as you are online i'm most likely online again too by that time :)

Thanks for your work, appreciated.

Op di 22 nov. 2016 00:32 schreef Gnat008 <notifications@github.com>:

**Comment by Gnat008** [comment] 2016-11-22 17:25
@Sikatsu I would have used a pm, but I can't figure out how to do that on this. lol. But I am here now.

**Comment by Sikatsu** [comment] 2016-11-22 17:27
Ohh, I used the wrong word lol. Just meant a message, sorry. Coming =)

**Comment by Gnat008** [comment] 2016-11-22 18:01
[perworldinventory-1.9.0.zip](https://github.com/Gnat008/PerWorldInventory/files/607175/perworldinventory-1.9.0.zip)

**Comment by Gnat008** [comment] 2016-11-22 18:56
@J2D22 @mibby @sloanr333 @Elijeh 
A fix for this should finally be released on Spigot. Everything is working on @Sikatsu 's server now. If some of you guys could make sure everything is working on your ends, that would be great! Thanks!

**Comment by Toodo** [comment] 2016-11-22 23:50
@gnat008 does it work for 1.10 perworldinventory-1.9.0.zip?

**Comment by Gnat008** [comment] 2016-11-22 23:51
@Toodo The download from the Spigot website should work on 1.10.

**Comment by Toodo** [comment] 2016-11-23 00:05
yes i know but i just asking if it works to 1.10 so i can help out and try it out :)

**Comment by Gnat008** [comment] 2016-11-23 00:06
Uhh well, it's the same file, so.. Yes.

**Closed** 2017-09-27 18:06 UTC
Labels: Priority: Critical, Status: Fixed, Type: Bug
